### ISSUE TITLE
Register Asset : Info Copy

### ISSUE THREAD

**Issue by MarkHinojosa** [HERCone/herc-edge-login#74]
The Info Button Copy is too stark white on the back ground. 
can we make it better ?

**Comment by MarkHinojosa** [comment]
"i think putting it in a rounded bubble
encasing it in something rather than having it be loose
would help
maybe a rounded transparent bubble with a black border with white text
would help the eyes
also! at least 1.5 spacing
and make the font bigger"

**Comment by lrgeoemtry** [comment]
good job team!
